# =========================
# JVM / Gradle 性能设置
# =========================
org.gradle.jvmargs=-Xmx4G -Xms1G -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# 网络设置
systemProp.java.net.preferIPv4Stack=true
# =========================
# Minecraft / NeoForge 版本
# =========================
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.64-beta
mod_loader=neoforge
# =========================
# Mod 基本信息
# =========================
mod_id=localmusicmod
mod_name=LocalMusicMod
mod_license=MIT license
mod_version=1.0.0
mod_group_id=github.com.gengyouno
mod_authors=gengyoubo
