{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyouno",
    "module": "LocalMusicMod",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.1-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.1-26.1.2-neoforge.jar",
          "size": 35106,
          "sha512": "e121a77a2983661ef61cf23522c4b4f21ed9cbc614f6dcf02e3ce4b5016bc69e2c351b5996ec6ec740030178328b26bbbdd626ad7fe493484d3b530350a9febd",
          "sha256": "3aba7ba3b8e3e3e241ba17d7915fdf8d791e239acfafb5d8573a0dccdeeb54d0",
          "sha1": "2bf64b337cc5602c29dfcb55f650611043a2cd61",
          "md5": "60a581e4303cdb1e725b4b02adbb53b4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.1-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.1-26.1.2-neoforge.jar",
          "size": 35106,
          "sha512": "e121a77a2983661ef61cf23522c4b4f21ed9cbc614f6dcf02e3ce4b5016bc69e2c351b5996ec6ec740030178328b26bbbdd626ad7fe493484d3b530350a9febd",
          "sha256": "3aba7ba3b8e3e3e241ba17d7915fdf8d791e239acfafb5d8573a0dccdeeb54d0",
          "sha1": "2bf64b337cc5602c29dfcb55f650611043a2cd61",
          "md5": "60a581e4303cdb1e725b4b02adbb53b4"
        }
      ]
    }
  ]
}
