{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyouno",
    "module": "LocalMusicMod",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "size": 42256,
          "sha512": "c5fae5355624a52bd33e9a3531e4c7e9893d24ea90e20aafd3129a35f8a338e0d98e9b02cb9bf5a2bd1cd21fb827c50ba174b64134cdb24f2a5117bf25a2ec43",
          "sha256": "f3dc7509b4d3255f86935038bef1f82df23deef39e3c8d59243325306e56b85e",
          "sha1": "200ca80d7cec416a7aaed2f13059a5e5e927ed6a",
          "md5": "75827db3b1651f64175d93a3a74a47fb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "size": 42256,
          "sha512": "c5fae5355624a52bd33e9a3531e4c7e9893d24ea90e20aafd3129a35f8a338e0d98e9b02cb9bf5a2bd1cd21fb827c50ba174b64134cdb24f2a5117bf25a2ec43",
          "sha256": "f3dc7509b4d3255f86935038bef1f82df23deef39e3c8d59243325306e56b85e",
          "sha1": "200ca80d7cec416a7aaed2f13059a5e5e927ed6a",
          "md5": "75827db3b1651f64175d93a3a74a47fb"
        }
      ]
    }
  ]
}
