{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyouno",
    "module": "LocalMusicMod",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "size": 42202,
          "sha512": "6e1a7cbdb2db8edd89a40a8fb5ebb7fb42934c5aa1b9d1d879cabfa25b37ad06f9a533efb7739ae4e94c1c004a2c2bb523d44f4b883e0906b80a8e89572d62a6",
          "sha256": "4e6342506597d75565a0b156fb1902bba2b21759739e964b1de8a66f82aec00f",
          "sha1": "b2bb82b4e066268c4a3a43a7266e3ddb7cf10752",
          "md5": "1131315f9f1cbecac0356ad6030c142e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.2-26.1.2-neoforge.jar",
          "size": 42202,
          "sha512": "6e1a7cbdb2db8edd89a40a8fb5ebb7fb42934c5aa1b9d1d879cabfa25b37ad06f9a533efb7739ae4e94c1c004a2c2bb523d44f4b883e0906b80a8e89572d62a6",
          "sha256": "4e6342506597d75565a0b156fb1902bba2b21759739e964b1de8a66f82aec00f",
          "sha1": "b2bb82b4e066268c4a3a43a7266e3ddb7cf10752",
          "md5": "1131315f9f1cbecac0356ad6030c142e"
        }
      ]
    }
  ]
}
