{
  "formatVersion": "1.1",
  "component": {
    "group": "github.com.gengyouno",
    "module": "LocalMusicMod",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.3-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.3-26.1.2-neoforge.jar",
          "size": 71415,
          "sha512": "ebd2c3f77fc70b87653c30c5085fb9704d99b3d750d0dd67a54245aba174c22f4d1ac3739a68099ee5420d9d714849ff3b6ab215cfb04801d14f6270b6f89ce0",
          "sha256": "1bf334f81f432f0f3531c4ccf1caa6390a35691e5bbf35ae53493c7119e8d643",
          "sha1": "bb45e649f3e871167aac7854ad9632244516a55e",
          "md5": "f4e12f63bd673ef10129a6a5a6e712ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "LocalMusicMod-1.0.3-26.1.2-neoforge.jar",
          "url": "LocalMusicMod-1.0.3-26.1.2-neoforge.jar",
          "size": 71415,
          "sha512": "ebd2c3f77fc70b87653c30c5085fb9704d99b3d750d0dd67a54245aba174c22f4d1ac3739a68099ee5420d9d714849ff3b6ab215cfb04801d14f6270b6f89ce0",
          "sha256": "1bf334f81f432f0f3531c4ccf1caa6390a35691e5bbf35ae53493c7119e8d643",
          "sha1": "bb45e649f3e871167aac7854ad9632244516a55e",
          "md5": "f4e12f63bd673ef10129a6a5a6e712ca"
        }
      ]
    }
  ]
}
